### PR TITLE
Remove poltergeist dependency

### PR DESCRIPTION
**Pull request by paresharma**
@rprt/owners 
https://github.com/rprt/rspec-page-regression/issues/10 Remove poltergeist dependency and update Readme.

### CODE REVIEW

**Comment by ronen** [comment]
@paresharma looks good.  just my usual pickiness :)

**Comment by paresharma** [comment]
Yeap, there's no limit to how good a Readme can be. I'll clean it up and also remove `Notes on Version` with this PR :)

**Comment by ronen** [comment]
> Yeap, there's no limit to how good a Readme can be.

:) Indeed!

Would you mind doing that last cleanup I mentioned too as long as you're in this (remove "There are no other external...") if you agree with it?  Then either way you can go ahead and merge I'd say.

**Comment by paresharma** [comment]
Yeah, I think we can remove it. Besides GitHub's online markdown editor is so cool and makes editing markdown and committing the changes so easy. :+1:

**Comment by paresharma** [comment]
Merging it now. We still have a few more PR's to further our discussions. :smiling_imp:

**Pull request merged**
