### PR TITLE
Screenshot labels

### PR DESCRIPTION
**Pull request by Earendil95**

### CODE REVIEW

**Comment by palkan** [comment]
Fixes #26.

**Comment by paresharma** [comment]
Looks good to me. Thanks @palkan @Earendil95.

**Comment by jekuno** [comment]
Currently we get a directory structure as follows:
```
reference_screenshots/
    users/
         edit_user/
             expected.png
        new_user/
            expected-form_with_errors.png
            expected-form_valid.png
          show_user/
             expected.png
```

I would suggest that we strip off the last directory layer so that we get:

```
reference_screenshots/
    users/
        edit_user.png
        new_user-form_with_errors.png
        new_user-form_valid.png
        show_user.png
```

That way we save one layer of nested directories and can strip off the prefix "expected" which doesn't add any extra information.

What do you think?

**Comment by ronen** [comment]
Sorry just saw this!

Yes, I think you're right, it would be better to strip off a layer and have the filename be more useful than "expected.png".

**Pull request merged**
