### PR TITLE
Test multiple viewports

### PR DESCRIPTION
**Pull request by paresharma**
@rprt/owners 
This is the adaptation of the previous PR https://github.com/rprt/rspec-page-regression/pull/16.

This includes most of the WBN's that we discussed except, notable, for:
`WBN for the matcher to take options size: [:small, ...] and/or except_size: [:medium, ...]`.
Which I think can be taken up as a separate feature.

Do have a look :)

### CODE REVIEW

**Comment by ronen** [comment]
One more comment, that I don't have a specific best way to fix:  The code passes around `viewport` as a pair `[name, size]`, and then uses things like `viewport.first`, `viewport[1]`, `viewports.first.first` etc., all of which I personally find unclear.  So I'd suggest either 

a. cast the viewports into a class or just `Struct` or `OpenStruct` so that they can be accessed as `viewport.name` and `viewport.size`, or
b. just pass around `viewport_name` and `viewport_size` everywhere

Thoughts?

**Comment by paresharma** [comment]
Yeah, I actually have a version on my local where I pass around `viewport_name` and `viewport_size`. But I kinda like the first idea, I will try if I can restructure it in a better way with a Class or a Struct.

**Comment by ronen** [comment]
OK, I'd be fine either way.   Thanks for putting up with my pickiness!

**Comment by paresharma** [comment]
Ran my 1st 10k after a long-long time. So, here's some bonus commits. :runner: :smile:

**Comment by ronen** [comment]
> Ran my 1st 10k after a long-long time. So, here's some bonus commits. :runner: :smile:

Nice.  just took a 14+ hour two-leg plane trip with my 6-year-old.  So now going back to bed :)

**Comment by paresharma** [comment]
Ahh that's long, take rest. Meanwhile I do the change and commit. :+1:

**Comment by ronen** [comment]
Cool.  All looks good to me.

**Pull request merged**
