### PR TITLE
Viewport management

### PR DESCRIPTION
**Pull request by paresharma**
@ronen @jekuno 

This PR takes care of https://github.com/rprt/rspec-page-regression/issues/25.
Also, I have removed `reference_screenshot_path` option, I will try to introduce the `label` option in a separate PR, hopefully sometime soon.

I'll update the Readme accordingly, meanwhile do have a look. :)

### CODE REVIEW

**Comment by ronen** [comment]
Cool!  I'll look through it and see if I have any comments

**Comment by ronen** [comment]
@paresharma as you saw, just some small petty comments from me :)  Feel free to ignore or improve upon any of them.

**Comment by paresharma** [comment]
Merging in a few minutes, if anyone has anything to say now is the time or forever hold your silence. :smiling_imp:

**Comment by ronen** [comment]
Looks good to me!

**Pull request merged**
