### PR TITLE
Fixes #9

### LINKED ISSUE #9: Improve matcher and directory names
Follwing clean code coventions it would make sense to replace the `expectation` directory by a more descriptive name such as `reference_screenshots` (btw: note that the directory name should be pluralized similar to the directories 'features', 'factories' and 'models').

Accordingly I would suggest to introduce a more descriptive matcher name i.e. change it from `expect(page).to match_expectation` to `expect(page).to match_reference_screenshot`.

### PR DESCRIPTION
**Pull request by jekuno**
Fixes #9
Introduces new matcher and directory names for reference screenshots

### CODE REVIEW

**Comment by ronen** [comment]
Nice!  So much better than what I had before!!

I added a few small notes in in the commits for some minor things -- a typo, and no need i think to keep "(expectation images)" in the README section headings.  Want to see if those look OK to you?

**Comment by paresharma** [comment]
Some inline comments, else looks really good to me.

**Comment by jekuno** [comment]
Thanks for looking through it. I updated it using `reference` instead of `ref`. See https://github.com/jekuno/rspec-page-regression/commit/072c6b2ed8e39696c233d54912e352fa2157ebf7

**Comment by paresharma** [comment]
All in all this looks good to me. About the README, we will anyway tidy it up once we are about to do the final release. I'll leave the merge to you guys. :+1: 

I'll resume work on supporting a cleaner multiple viewports support.

**Comment by ronen** [comment]
I don't want (my) quibbling over the README to stand in the way of progress.  Merged

**Pull request merged**
